### ISSUE TITLE
Criteria for motion weights 

### ISSUE THREAD

**Issue by ameliacode** [nv-tlabs/ASE#17]
Hello again.
Right now I am implementing my own motion data for low level policy training 
I came across that each mocap data needs different weights.

Are there any criteria or formula for the weights in dataset yaml file?? 
I did check the paper, and there weren't any info for this..:(

and also, I have tried one of your dataset_rellusion.yaml with amp_humanoid.yaml and it resulted "stand still" rather than locomote.. 
It did worked well when training with single motion file tho.

I wonder what's wrong with it..

Another random question:
My GPU lacks of memory when training. Instead of tackling batch related parameters, I modifed the number of amp observation size in each task related yaml file. Does this affect severely on training ?

**Comment by xbpeng** [comment]
The weights adjust the likelihood of sampling data from different motion files. This is to balance the different types of motions in the dataset. For example, if we have a lot of motion data, then we might need to upweight data of other skills so that the model doesn't just learn to mostly perform locomotion skills. So let say if you have twice as much data for skill A as skill B, then you should give motions for skill A a weight of 1 and a weight of 2 for motions for skill B.

Training AMP on its own without any task objectives are prone to mode collapse. dataset_reallusion.yaml contains data for a lot of different skills, but with AMP there are not latent variables to select different skills, so the model tends to just collapse to a specific behaviors, like standing in your case. Try using ASE instead, it will not suffer from mode-collapse as much.

What do you mean by modify "number of amp observation size"?

**Comment by ameliacode** [comment]
Wow Thanks.

I may train with ASE as soon as I solve my gpu memory problem..
There is a numAMPObsSteps in environment yaml file.
If I understand it right, this parameter decides overall action space.

I just simply modified that parameter, and it did worked well when training. 
However, I am not sure amending the value relates to overall quality.
