### ISSUE TITLE
how to translate a  spherical joint to 3 revolute joints?

### ISSUE THREAD

**Issue by 3-body** [nv-tlabs/ASE#42]
Hi, Jason, Thanks for your great work! It's very important to humanoid robot sim. or dev.!
I want to model and sim a humanoid robot with all revolute joints, so need to translate ASE/AMP character model's spherical joint to revolute joints, could u give me some advice/example?

**Comment by xbpeng** [comment]
Our simulator supports revolute joints. The knees and elbows are already modeled as revolute joints:
https://github.com/xbpeng/DeepMimic/blob/70e7c6b22b775bb9342d4e15e6ef0bd91a55c6c0/data/characters/humanoid3d.txt#L93
So you can just use those instead of spherical joints for your robot, and the code should hopefully handle it automatically.

**Comment by 3-body** [comment]
@xbpeng Thanks for your reply that's very useful to me.
