### ISSUE TITLE
About the blend in the function "get_motion_state"

### ISSUE THREAD

**Issue by mjdxyr** [nv-tlabs/ASE#57]
Hi! Your work is awesome.
I have a simple problem ,why "root_pos" in the function "get_motion_state" will blend but "root_ang_vel" does not blend?

**Comment by xbpeng** [comment]
this is mainly because if you keep the velocity constant between timesteps, it will ensure that if you start at the first keyframe, and integrate forward in time with the constant velocity, then it will eventually hit the second keyframe. However, if you linearly blend the velocities as well, then integrating the interpolated velocity will not necessarily guarantee that you will hit the next keyframe. So the velocities are not interpolated, and this also as the benefit of saving some compute.

**Comment by mjdxyr** [comment]
Thank you very much for your help!
