### ISSUE TITLE
How to specify motion files for task training?

### ISSUE THREAD

**Issue by floodsung** [nv-tlabs/ASE#8]
Hi,
There is no RL_Avatar_Crouch_Idle_Motion.npy in data/motions, how to specify motion files for  every different task training?

Also, I find weights in dataset_reallusion_sword_shield.yaml, how to determine the weights?

Thx

**Comment by xbpeng** [comment]
sorry, wrong file. I've fixed it in the readme. You can use whatever motion for task-training you want. It's just a placeholder, and not really being used in the actual training process.

The weights in dataset_reallusion_sword_shield.yaml are manually specified, so that the samples are more balanced across skills.

**Comment by floodsung** [comment]
Thx a lot!
